import type { PortfolioCategory, PortfolioItem } from "@/lib/portfolio-types";

import portfolioManifest from "./portfolio-manifest.json";

const CATEGORY_ORDER: PortfolioCategory[] = [
  "Web Applications",
  "E-Commerce Solutions",
  "Mobile Applications",
];

function categorySortKey(category: PortfolioCategory): number {
  const i = CATEGORY_ORDER.indexOf(category);
  return i === -1 ? CATEGORY_ORDER.length : i;
}

/**
 * Portfolio items from lib/portfolio-manifest.json (generated by
 * `node scripts/generate-portfolio-manifest.mjs` via npm prebuild).
 * Images are served as static files from /images/projects/** (not via API routes),
 * so Vercel serverless bundles stay under the 250MB limit.
 */
export function getPortfolioItems(): PortfolioItem[] {
  const items = portfolioManifest as PortfolioItem[];
  return [...items].sort(
    (a, b) => categorySortKey(a.category) - categorySortKey(b.category)
  );
}
